version: "3.8"

services:
  mongo:
    image: mongo:latest
    ports:
      - "27020:27017"
    volumes:
      - ./mongo_data:/data/db
  api:
    build:
      context: .
      dockerfile: Containerfile
    ports:
      - "3001:3001"
    env_file:
      - ./packages/api/.env
