name: "Deploy Backend"

on:
  push:
    branches: ["main"]
    paths: ["packages/api/**", "packages/shared/**"]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_ADDRESS }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd resumeboost
            git fetch
            git reset --hard origin/main
            podman-compose up --build api -d
